version: "3"
services:
  manager-api:
    container_name: manager-api
    build:
      context: .
      dockerfile: Dockerfile
    image: "manager-api:${APP_VERSION}"
    ports:      
      - "${APP_PORT_DOCKER}:3000"
    depends_on:
      - manager-db      
    env_file:
      - prod.env
    restart: always
  manager-db:
    container_name: manager-db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_SCHEMA}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    env_file:
      - prod.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: always

volumes:
  data: